name: "Frogbot Scan Repository"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main"]
    steps:
      - uses: jfrog/frogbot@v3
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_USE_CONFIG_PROFILE: "false"
        with:
          oidc-provider-name: Liquid-Frog/npm-frogbotV3-demo@github
